apiVersion: v1
kind: Service
metadata:
  name: gpu-admission
  namespace: kube-system
spec:
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 3456
  selector:
    component: scheduler
    tier: control-plane
    app: gpu-admission
  type: ClusterIP